# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "longread_mapping"
description: Map long reads to a reference genome with minimap 2 and sort the output BAM files
keywords:
  - align
  - fasta
  - genome
  - reference
  - bam
components:
  - minimap2_alignment
  - bam_sort_stats_samtools
  - clair3
  - bcftools/sort
  - bcftools/index
  - bcftools/filter
  - bcftools/stats
  - consensus_bcftools
  - seqtk/comp
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - ch_fasta:
      type: file
      description: Reference fasta file
      pattern: "*.{fasta,fa}"
  - ch_faidx:
      type: file
      description: samtools reference genome index files
      pattern: "*.fai"
  - ch_reads:
      type: file
      description: |
        List of input FastQ files
output:
  - bam:
      type: file
      description: |
        Channel containing BAM files
        Structure: [ val(meta), path(bam) ]
      pattern: "*.bam"
  - bai:
      type: file
      description: |
        Channel containing indexed BAM (BAI) files
        Structure: [ val(meta), path(bai) ]
      pattern: "*.bai"
  - vcf:
      type: file
      description: |
        Channel containing Sorted VCF files
        Structure: [ val(meta), path(vcf) ]
      pattern: "*.{vcf.gz}"
  - csi:
      type: file
      description: |
        Channel containing CSI files
        Structure: [ val(meta), path(csi) ]
      pattern: "*.csi"
  - tbi:
      type: file
      description: |
        Channel containing TBI files
        Structure: [ val(meta), path(tbi) ]
      pattern: "*.tbi"
  - stats:
      type: file
      description: |
        Channel containing bcftools stats files
        Structure: [ val(meta), path(tbi) ]
      pattern: "*.txt"
  - consensus:
      type: file
      description: |
        Channel containing consensus FASTA files
        Structure: [ val(meta), path(consensus) ]
      pattern: "*.fa"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@opetryk"
  - "@avantonder"
maintainers:
  - "@avantonder"
